---
title: "A strategic change of pace for public-facing communication"
description: |
  Why my messages have slowed down.
author: Will Landau
date: 10-04-2023
output:
  distill::distill_article:
    self_contained: false
categories:
  - communication
  - community
  - productivity
preview: image.jpg
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Background

I love to create and maintain open-source software. It is a joy to write code to solve problems, release solutions for everyone, and keep packages working so problems stay solved. I want to keep developing and engineering for as long as possible.

## Problem

Although I value and grow from user feedback, I now face an overwhelming volume of questions and requests about the projects I maintain. Requests come at all times of day on all days of the week, and each response is a context switch. The high throughput wears me down.

## Solution

Late last month, I created digital boundaries to protect my mental health and productivity. My GitHub notifications, social media, and package maintainer identity now use a special email account that I only check on certain days of the week. The benefits were immediate, and the changes are here to stay.

## What this means for users

I send most of my messages during the middle part of the week, usually Wednesdays. I may be slower to communicate than in previous years, but I am still committed to helping users. And I am not slowing down at all when it comes to actual software engineering. Far from it: these communication boundaries are giving me more time and energy to fix bugs, add new features, and create new packages.

## How you can help

If you use [`targets`](https://github.com/ropensci/targets), [`crew`](https://github.com/wlandau/crew), or any of my other packages, I would be grateful for help answering GitHub issues and discussions, especially at <https://github.com/ropensci/targets/discussions>. And if you are posting a request yourself, please respect the communication and reproducibility guidelines that I describe at <https://books.ropensci.org/targets/help.html>.
