---
title: Presentations
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- **Landau, W.**, and Stock, C., and Bean, A., and Sidi, Y., and Kunzmann, K. (2004) "{brms.mmrm}: a modern R package for Bayesian MMRMs." Bayesian Biostatistics Conference, <https://bayes-pharma.org/wp-content/uploads/2024/11/Will-Landau.pdf>.
- Gao, C., and **Landau, W.**. (2024) "{mirai} and {crew}: next-generation async to supercharge {promises}, Plumber, Shiny, and {targets}", Posit Conference, <https://www.youtube.com/watch?v=s_cBi155ZIQ>.
- Scott, E., and Nitta, J., and **Landau, W.**. (2023) "{targets} in Action." rOpenSci Community Call, <https://ropensci.org/commcalls/jan2023-targets/>.
- **Landau, W.**, and Man, A., and Kemmer, P., and Chatterjee, S., and Bian, F., and Zhao, H., and Zhao, Z. (2022) "Bayesian methods for placebo borrowing in master protocols." Bayesian Biostatistics 2022 Conference, <https://bayes-pharma.org/>.
- **Landau, W.** (2022) "Data version control for reproducible analysis pipelines in R." useR! 2022 Conference, <https://github.com/wlandau/user-conf-2022/>.
- **Landau, W.** (2021) "Target Markdown and {stantargets} for Bayesian model validation pipelines", R/Medicine 2021 Conference, <https://github.com/wlandau/rmedicine2021-slides>.
- **Landau, W.** (2021) "Reproducible computation at scale in R with targets", Lille R User Meetup Group, <https://github.com/wlandau/r-lille-2021>.
* **Landau, W.** (2021) "Reproducible computation at scale in R with targets", UK National Health Service R Community Conference 2021, half-day short course, <a href="https://github.com/wlandau/targets-tutorial">https://github.com/wlandau/targets-tutorial</a>.
* **Landau, W.** (2021) "stantargets and Target Markdown for Bayesian model validation pipelines", Bayes@Lund Meetup, <https://github.com/wlandau/bayes-lund-2021>.
- **Landau, W.** (2020) "Reproducible computation at scale with targets", New York Open Statistical Programming Meetup, <https://github.com/wlandau/nyhackr2020>.
- **Landau, W.** (2020) "Reproducible computation at scale with targets", Los Angeles R Users Meetup, <https://github.com/wlandau/larug2020>.
- **Landau, W.** (2020) "Reproducible computation at scale with targets", R/Pharma 2020 Conference, half-day short course, <https://github.com/wlandau/targets-tutorial>.
- **Landau, W.** (2020) "Reproducible computation at scale with targets", R/Pharma 2020 Conference, presentation, <https://github.com/wlandau/rpharma2020>.
- **Landau, W.** (2020) "Reproducible computation at scale with drake", R/Medicine Conference. <https://wlandau.github.io/rmedicine2020>.
- **Landau, W.** (2020) "Reproducible computation at scale with drake", useR! 2020 Conference, half-day short course, <https://github.com/wlandau/learndrake>.
- **Landau, W.** (2019) "Reproducible workflows at scale with drake", rOpenSci Community Call, <https://ropensci.org/commcalls/2019-09-24/>h.
- **Landau, W.** (2019) "Machine learning workflow management with drake", invited 4-hour workshop, R/Pharma Conference.
- **Landau, W.** (2019) "Reproducible Computation at Scale in R", Harverd DataFest.
- **Landau, W.** (2018) "The drake R package: reproducible data analysis at scale", R/Pharma Conference.
- **Landau, W.**, and Niemi, J. (2016), "A Fully Bayesian Strategy for High-Dimensional Hierarchical Modeling Using Massively Parallel Computing". *Joint Statistical Meetings*, Section on Statistical Computing, Section on Statistical Graphics, Statistical Computing and Graphics Student Awards — Topic Contributed Papers. <a href="https://ww2.amstat.org/meetings/jsm/2016/onlineprogram/AbstractDetails.cfm?abstractid=318764">https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645</a>.
- **Landau, W.**, and Liu, P. (2013), "Dispersion Estimation and Its Effect on Test Performance in RNA-Seq Data Analysis". *Joint Statistical Meetings*,	Biometrics Section, contributed poster. <a href="https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645">https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645</a>.
