---
title: Resume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<div style="float:left; width: 60%">
<h2>Education</h2>
<ul>
  <li>PhD Statistics, <a href="http://www.iastate.edu/">Iowa State U</a>, 2016</li>
  <li>MS Statistics, <a href="http://www.iastate.edu/">Iowa State U</a> 2013</li>
  <li>BS Math, <a href="http://www.uchicago.edu/">U of Chicago</a> 2011</li>
</ul>
</div>

<div style="float:right; width: 40%">
<h2>Contact</h2>
<ul>
  <li>will _dot_ landau at gmail _dot_ com</li>
  <li><a href="http://wlandau.github.io">wlandau.github.io</a></li>
  <li><a href="http://linkedin.com/in/wlandau">linkedin.com/in/wlandau</a></li>
  <li><a href="http://github.com/wlandau">github.com/wlandau</a></li>
</ul>
</div>

## Select Publications

* **Landau, W.** (2021), "We Need Trustworthy R Packages", The R Journal, 2021. <https://doi.org/10.32614/RJ-2021-109>.
* **Landau, W.** (2021), The stantargets R package: a workflow framework for efficient reproducible Stan-powered Bayesian data analysis pipelines. Journal of Open Source Software, 6(60), 3193, <https://doi.org/10.21105/joss.03193>.
* Chakladar, S., Liao, R., **Landau, W.**, Gamalo, M., Wang, Y. (2021). "Discrete Time Multi-State Model with Regime Switching for Modelling COVID-19 Disease Progression and Clinical Outcomes." *Statistics in Biopharmaceutical Research*, accepted, <https://doi.org/10.1080/19466315.2021.1880966>.
* **Landau, W.** (2021), "The targets R package: a dynamic Make-like function-oriented pipeline toolkit for reproducibility and high-performance computing". *Journal of Open Source Software*, 6(57), 2959, <https://doi.org/10.21105/joss.02959>.
* <b>Landau, W.</b>, Niemi, J., and Nettleton, D., "Fully Bayesian analysis of RNA-seq counts for the detection of gene expression heterosis". *Journal of the American Statistical Association*,  <a href="https://doi.org/10.1080/01621459.2018.1497496">https://doi.org/10.1080/01621459.2018.1497496</a>.
* <b>Landau, W.</b> and Liu, P. (2013), "Dispersion Estimation and Its Effect on Test Performance in RNA-seq Data Analysis: A Simulation-Based Comparison of Methods," *PLOS One*, 8. Available at
<a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0081415">journals.plos.org</a>.

## Select presentations

* Scott, E., and Nitta, J., and **Landau, W.**. (2023) "{targets} in Action." rOpenSci Community Call, <https://ropensci.org/commcalls/jan2023-targets/>.
* **Landau, W.**, and Man, A., and Kemmer, P., and Chatterjee, S., and Bian, F., and Zhao, H., and Zhao, Z. (2022) "Bayesian methods for placebo borrowing in master protocols." Bayesian Biostatistics 2022 Conference, <https://bayes-pharma.org/>.
* **Landau, W.** (2022) "Data version control for reproducible analysis pipelines in R." useR! 2022 Conference, <https://github.com/wlandau/user-conf-2022/>.
* **Landau, W.** (2021) "Target Markdown and {stantargets} for Bayesian model validation pipelines", R/Medicine 2021 Conference, <https://github.com/wlandau/rmedicine2021-slides>.
* **Landau, W.** (2020) "Reproducible computation at scale with targets", New York Open Statistical Programming Meetup, <https://github.com/wlandau/nyhackr2020>.
* **Landau, W.** (2020) "Reproducible computation at scale with targets", R/Pharma 2020 Conference, half-day short course, <https://github.com/wlandau/targets-tutorial>.
* **Landau, W.** (2019) "Machine learning workflow management with drake", invited 4-hour workshop, R/Pharma Conference.
* **Landau, W.**, and Niemi, J. (2016), "A Fully Bayesian Strategy for High-Dimensional Hierarchical Modeling Using Massively Parallel Computing". *Joint Statistical Meetings*, Section on Statistical Computing, Section on Statistical Graphics, Statistical Computing and Graphics Student Awards — Topic Contributed Papers. <a href="https://ww2.amstat.org/meetings/jsm/2016/onlineprogram/AbstractDetails.cfm?abstractid=318764">https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645</a>.
* **Landau, W.**, and Liu, P. (2013), "Dispersion Estimation and Its Effect on Test Performance in RNA-Seq Data Analysis". *Joint Statistical Meetings*,	Biometrics Section, contributed poster. <a href="https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645">https://ww2.amstat.org/meetings/jsm/2013/onlineprogram/AbstractDetails.cfm?abstractid=307645</a>.

## Select open-source software

* [rOpenSci](https://ropensci.org/) packages [`targets`](https://github.com/ropensci/targets), [`tarchetypes`](https://github.com/ropensci/tarchetypes), and [`gittargets`](https://github.com/ropensci/gittargets) for general-purpose reproducible analysis pipelines.
* [`stantargets`](https://github.com/ropensci/stantargets) and [`jagstargets`](https://github.com/ropensci/jagstargets) for Bayesian data analysis pipelines.
- [`crew`](https://github.com/wlandau/crew): a [`mirai`](https://github.com/shikokuchuo/mirai)-powered worker launcher framework.
- [`crew.cluster`](https://github.com/wlandau/crew.cluster): [`crew`](https://github.com/wlandau/crew) launcher plugins for traditional clusters.
* [`historicalborrow`](https://github.com/wlandau/historicalborrow) and [`historicalborrowlong`](https://github.com/wlandau/historicalborrowlong) for Bayesian historical borrowing methods for clinical trials.

## Awards

* 2023 Lilly Innovator Award. Awarded for developing a novel cloud-based computing framework to accelerate clinical trial design.
* 2021 Lilly Innovator Award. Awarded for creating the R package [`targets`](https://docs.ropensci.org/targets) and its associated ecosystem to track workflow that empowers reproducible analytical research with efficiency.
* 2020 Lilly Innovator Award. Awarded for the development of efficient clinical trial simulation software needed for complex designs and trials of potential COVID-19 treatments.
* 2019 NumFOCUS New Contributor Recognition. Awarded for inclusive and collaborative work with rOpenSci. <a href="https://numfocus.org/blog/2019-numfocus-awards">https://numfocus.org/blog/2019-numfocus-awards</a>.
* 2017 Lilly Innovator Award. Awarded for leading a successful team effort to modernize Lilly's internal process for contributing open source software.
* <a href="http://stat-computing.org/awards/student/winners.html">Student Paper Award</a>, American Statistical Association Section on Statistical Computing, Jan 2016. Awarded for an early draft of the preprint at <a href="http://arxiv.org/abs/1606.06659">arxiv.org/abs/1606.06659</a>.
* [Vince Sposito Statistical Computing Award](https://stat.iastate.edu/graduate-financial-support), Iowa State University, Aug 2013.
* [GlaxoSmithKline Industrial Scholarship](https://stat.iastate.edu/graduate-financial-support), Iowa State University, Sep 2011.
* Alumni Scholarship, Iowa State University, Aug 2011.

## Skills

- Bayesian methods, Markov chain Monte Carlo, hierarchical models, high-dimensional data analysis, linear and nonlinear models, clinical trial simulation and design.
- Reproducible analysis pipelines, high-performance computing, R, package development, Stan, JAGS.
- Past experience with machine learning, C++, C, CUDA, Python, JavaScript, Fortran.

## Senior Research Scientist
- **October 2021 - present**
- [Eli Lilly and Company](http://www.lilly.com)
- Developed Bayesian methods and proprietary software packages that were influential in the analyses and decision-making of clinical trials in Alzheimer's and chronic pain.
- Created significant extensions to the {targets} R package and its ecosystem for Bayesian data analysis, data versioning, and cloud storage.

## Research Scientist
- **October 2016 - October 2021**
- [Eli Lilly and Company](http://www.lilly.com)
- Created popular open-source rOpenSci packages such as [`targets`](https://docs.ropensci.org/targets) for reproducible analysis pipelines in R.
- Drove the standardization and automation of Bayesian methods in the analysis of clinical trials.
- Led the successful transformation of the internal tool suite for the simulation and design of clinical trials.
- Increased company-wide external engagement with the R and open-source software (OSS) communities. Modernized internal processes to allow substantial contribution to OSS and served as a gatekeeper for new OSS disclosures.
- Lead statistician in early-phase autoimmune asset teams.

## Research assistant
- **May 2013 - Aug 2016**
- RNA-sequencing Working Group, Department of Statistics, [Iowa State University](http://www.iastate.edu).
- Funded by NIH grant R01GM109458 with Drs. Dan Nettleton and Jarad Niemi.
- Developed a new fully Bayesian analysis method for high-dimensional genomic datasets using hierarchical models.
- Implemented massively parallelized Markov chain Monte Carlo.
- Created the 
<a href="https://github.com/wlandau/fbseq">fbseq</a>
R package to distribute the analysis method.
- Implemented and distributed parallel computing backends for [CUDA GPUs](https://developer.nvidia.com/about-cuda) (<a href="https://github.com/wlandau/fbseqCUDA">fbseqCUDA</a>) and [OpenMP](https://en.wikipedia.org/wiki/OpenMP) (<a href="https://github.com/wlandau/fbseqOpenMP">fbseqOpenMP</a>).
- Created the 
<a href="http://wlandau.github.io/remakeGenerator">remakeGenerator</a>, 
<a href="http://wlandau.github.io/parallelRemake">parallelRemake</a>, and 
<a href="http://wlandau.github.io/downsize">downsize</a> packages to manage, ameliorate, expedite, and accelerate computationally heavy reproducible workflows that are under heavy development.

## Seminar instructor

- **Aug - Dec, 2012 and 2013**.
- Department of Statistics, [Iowa State University](http://www.iastate.edu).
- [GPU computing](http://www.nvidia.com/object/what-is-gpu-computing.html) seminar series at <a href="http://wlandau.github.io/gpu">wlandau.github.io/gpu</a>.
- Educated faculty and graduate students on massively parallel computing with [general-purpose graphics processing units](http://www.nvidia.com/object/what-is-gpu-computing.html).
- Constructed, curated, and distributed slides, video, and example code at <a href="http://wlandau.github.io/gpu">wlandau.github.io/gpu</a> and on <a href="https://www.youtube.com/watch?v=VL3qbqA_Xco&list=PLs5XGFlsJ8Wi635Ig2QX3dbmJCNpss4aT">YouTube</a>.

## Course instructor
- **Jan - May, 2012 and 2013**.
- Department of Statistics, [Iowa State University](http://www.iastate.edu).
- STAT 305: Engineering Statistics (<a href="http://wlandau.github.io/stat305/">wlandau.github.io/stat305</a>).

## Grader
- **Aug - Dec, 2011**.
- Department of Statistics, [Iowa State University](http://www.iastate.edu).
- STAT 231: Engineering Probability.
- STAT 105: Introduction to Engineering Statistics.

## Leadership in Indianapolis

- Member of the board of directors, Friends of Fort Harrison State Park. May 2022 - present.
- Organizer and leader of volunteer bi-monthly park maintenance sessions at Fort Harrison. Sessions focus on removing and controlling invasive plants. May 2023 - present.

## Leadership at Eli Lilly and Company

- Led a successful team effort to modernize Lilly's internal procedure for contributing open source software.
- Served as a volunteer moderator in the [2017 National Science Bowl (high school Indiana Regionals)](https://science.energy.gov/wdts/nsb/regional-competitions/high-school-regionals/in_indiana-regional-high-school-science-bowl/).

## Leadership at Iowa State University

- Founder and leader, Cloud Computing Working Group, Sep - Dec 2015.
- Member, Computation Advisory Committee, Sep 2015 - May 2016.
- Volunteer instructor, Office of Precollegiate Programs for Talented and Gifted ([OPPTAG](http://www.opptag.iastate.edu)), Mar 13, 2014.
- Fellow, [Preparing Future Faculty](http://www.celt.iastate.edu/graduate-students-postdocs/preparing-future-faculty), Aug 2013 - May 2014.
- Assistant Coach, Boxing Club, Aug 2013 - Dec 2013.

## References

- <a href="http://jarad.me/">Jarad Niemi</a>, PhD advisor and major professor, [niemi@iastate.edu](mailto:niemi@iastate.edu).
- <a href="http://www.public.iastate.edu/~dnett/">Dan Nettleton</a>, lead principal investigator of the RNA-sequencing Working Group (Iowa State Department of Statistics), [dnett@iastate.edu](mailto:dnett@iastate.edu).
- <a href="http://www.public.iastate.edu/~pliu/">Peng Liu</a>, MS advisor and major professor, [pliu@iastate.edu](mailto:pliu@iastate.edu).
- Additional references available on request.

## Hobbies

- Climbing, Brazillian Jiu Jitsu, sailing, windsurfing
