---
title: Software
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Select works

### R package repositories

* [R-multiverse](https://r-multiverse.org), a community-curated dual repository fro Ro packages, powered by open-source [R-universe](https://r-universe.dev) infrastructure.

### Reproducible analysis pipelines

* [`targets`](https://github.com/ropensci/targets), dynamic function-oriented Make-like workflows for R. Long-term successor to [`drake`](https://github.com/ropensci/drake).
* [`tarchetypes`](https://github.com/ropensci/tarchetypes), general-use archetypes for targets and pipelines, including [parameterized Quarto at scale](https://docs.ropensci.org/tarchetypes/reference/tar_quarto_rep.html).

### Bayesian statistics pipelines

* [`stantargets`](https://github.com/ropensci/stantargets), Reproducible Bayesian data analysis pipelines with [`targets`](https://github.com/ropensci/targets) and [`cmdstanr`](https://github.com/stan-dev/cmdstanr). 
* [`jagstargets`](https://github.com/ropensci/stantargets), Reproducible Bayesian data analysis pipelines with [`targets`](https://github.com/ropensci/targets) and [`R2jags`](https://github.com/suyusung/R2jags).

### Statistical methods

* [`brms.mmrm`](https://github.com/openpharma/brms.mmrm): a modern R package for Bayesian mixed models for repeated measures (MMRMs).
* [`historicalborrow`](https://github.com/wlandau/historicalborrow): non-longitudinal hierarchical and mixture models for historical borrowing.
* [`historicalborrowlong`](https://github.com/wlandau/historicalborrowlong): a longitudinal hierarchical model for historical borrowing.

### Distributed computing

* [`crew`](https://github.com/wlandau/crew): a [`mirai`](https://github.com/shikokuchuo/mirai)-powered worker launcher framework.
* [`crew.cluster`](https://github.com/wlandau/crew.cluster): [`crew`](https://github.com/wlandau/crew) launcher plugins for traditional clusters.
* [`crew.aws.batch`](https://github.com/wlandau/crew.aws.batch): a [`crew`](https://github.com/wlandau/crew) launcher plugin for AWS Batch.

## Other packages

### R package utilities and infrastructure

* [`proffer`](https://github.com/r-prof/proffer): [`pprof`](https://github.com/google/pprof)-based profiler for R code.
* [`txtq`](https://github.com/wlandau/txtq): a small text-based message queue for parallel processes.

### Dissertation research

* [fbseq](https://github.com/wlandau/fbseq) Fully-Bayesian GPU-accelerated analysis of RNA-seq data ([arXiv preprint](http://arxiv.org/abs/1606.06659)).
* [fbseqCUDA](https://github.com/wlandau/fbseqCUDA) CUDA GPU support for [fbseq](https://github.com/wlandau/fbseq).
* [fbseqOpenMP](https://github.com/wlandau/fbseqOpenMP) OpenMP support for [fbseq](https://github.com/wlandau/fbseq).

### Prior work on reproducible analysis pipelines

* [`gittargets`](https://github.com/ropensci/gittargets), local data version control for the [`targets`](https://github.com/ropensci/targets) R package.
* [`drake`](https://github.com/ropensci/drake) an R-focused pipeline toolkit for data analysis projects. Featured in the [rOpenSci blog](https://ropensci.org/blog/2018/02/06/drake/) and [R Podcast Episode 22](https://r-podcast.org/episode/022-diving-in-to-drake-with-will-landau/).
* [`remakeGenerator`](https://www.github.com/wlandau/remakeGenerator) Generate large [`remake`](https://github.com/richfitz/remake)-style workflows.
* [`parallelRemake`](https://www.github.com/wlandau/parallelRemake) Parallel computing support for [`remake`](https://github.com/richfitz/remake).
